server:
  port: 8086
spring:
  application:
    name: audio-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stu-project-test.qingxu.website:10002/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: 
    password: 
  jpa:
    database:  MySQL
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: stu-project-test.qingxu.website
    port: 10004
    username: 
    password: 
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    #host: stu-project-test.qingxu.website
    host: stu-project-test.qingxu.website
    # Redis服务器连接端口
    port: 10003
    # Redis服务器连接密码（默认为空）
    password: 
    #连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 300
eureka:
  client:
    #是否向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心
    fetch-registry: true
    serviceUrl:
      defaultZone: http://stu-project-test.qingxu.website:10007/eureka/
  instance:
    prefer-ip-address: true #跨域访问
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

minio:
  endpoint: https://stu-project.qingxu.website
  accesskey: 
  secretkey: 
  port: 20511
  bucketName: audio