/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xu_testNative */

#ifndef _Included_com_xu_testNative
#define _Included_com_xu_testNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xu_testNative
 * Method:    result
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xu_testNative_result
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xu_testNative
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xu_testNative_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
